Object.assign(muban.mxpro.二级, {
  tabs: '.module-tab-item:gt(0)',
  //lists: '.module-row-one:eq(#id)&&a.module-row-text',
});
var rule = {
  模板: 'mxpro',
  title: 'Animoe动漫[漫]',
  host: 'https://animoe.org',
  url: '/show/fyclassfyfilter.html',
  searchUrl: '/search/page/fypage/wd/**.html',
  filter: {
    "20": [
      { "key": "分类", "name": "分类", "value": [{ "n": "全部", "v": "" }, { "n": "原创", "v": "/class/原创" }, { "n": "漫改", "v": "/class/漫改" }, { "n": "异世界", "v": "/class/异世界" }, { "n": "泡面番", "v": "/class/泡面番" }, { "n": "奇幻", "v": "/class/奇幻" }, { "n": "战斗", "v": "/class/战斗" }, { "n": "日常", "v": "/class/日常" }, { "n": "后宫", "v": "/class/后宫" }, { "n": "百合", "v": "/class/百合" }, { "n": "治愈", "v": "/class/治愈" }, { "n": "校园", "v": "/class/校园" }, { "n": "恋爱", "v": "/class/恋爱" }, { "n": "游戏改", "v": "/class/游戏改" }, { "n": "轻改", "v": "/class/轻改" }, { "n": "青春", "v": "/class/青春" }, { "n": "催泪", "v": "/class/催泪" }, { "n": "音乐", "v": "/class/音乐" }, { "n": "偶像", "v": "/class/偶像" }, { "n": "悬疑", "v": "/class/悬疑" }, { "n": "GAL改", "v": "/class/GAL改" }, { "n": "科幻", "v": "/class/科幻" }, { "n": "推理", "v": "/class/推理" }, { "n": "萝莉", "v": "/class/萝莉" }, { "n": "热血", "v": "/class/热血" }, { "n": "猎奇", "v": "/class/猎奇" }, { "n": "冒险", "v": "/class/冒险" }, { "n": "励志", "v": "/class/励志" }, { "n": "机战", "v": "/class/机战" }, { "n": "致郁", "v": "/class/致郁" }, { "n": "剧情", "v": "/class/剧情" }] },
      { "key": "年份", "name": "年份", "value": [{ "n": "全部", "v": "" }, { "n": "2023", "v": "/year/2023" }, { "n": "2022", "v": "/year/2022" }, { "n": "2021", "v": "/year/2021" }, { "n": "2020", "v": "/year/2020" }, { "n": "2019", "v": "/year/2019" }, { "n": "2018", "v": "/year/2018" }, { "n": "2017", "v": "/year/2017" }, { "n": "2016", "v": "/year/2016" }, { "n": "2015", "v": "/year/2015" }, { "n": "2014", "v": "/year/2014" }, { "n": "2013", "v": "/year/2013" }, { "n": "2012", "v": "/year/2012" }, { "n": "2011", "v": "/year/2011" }, { "n": "2010", "v": "/year/2010" }] },
      { "key": "字母", "name": "字母", "value": [{ "n": "字母", "v": "" }, { "n": "A", "v": "/letter/A" }, { "n": "B", "v": "/letter/B" }, { "n": "C", "v": "/letter/C" }, { "n": "D", "v": "/letter/D" }, { "n": "E", "v": "/letter/E" }, { "n": "F", "v": "/letter/F" }, { "n": "G", "v": "/letter/G" }, { "n": "H", "v": "/letter/H" }, { "n": "I", "v": "/letter/I" }, { "n": "J", "v": "/letter/J" }, { "n": "K", "v": "/letter/K" }, { "n": "L", "v": "/letter/L" }, { "n": "M", "v": "/letter/M" }, { "n": "N", "v": "/letter/N" }, { "n": "O", "v": "/letter/O" }, { "n": "P", "v": "/letter/P" }, { "n": "Q", "v": "/letter/Q" }, { "n": "R", "v": "/letter/R" }, { "n": "S", "v": "/letter/S" }, { "n": "T", "v": "/letter/T" }, { "n": "U", "v": "/letter/U" }, { "n": "V", "v": "/letter/V" }, { "n": "W", "v": "/letter/W" }, { "n": "X", "v": "/letter/X" }, { "n": "Y", "v": "/letter/Y" }, { "n": "Z", "v": "/letter/Z" }, { "n": "0-9", "v": "/letter/0-9" }] },
      { "key": "排序", "name": "排序", "value": [{ "n": "时间排序", "v": "/by/time" }, { "n": "人气排序", "v": "/by/hits" }, { "n": "评分排序", "v": "/by/score" }] }],
    "21": [
      { "key": "分类", "name": "分类", "value": [{ "n": "全部", "v": "" }, { "n": "原创", "v": "/class/原创" }, { "n": "漫改", "v": "/class/漫改" }, { "n": "异世界", "v": "/class/异世界" }, { "n": "泡面番", "v": "/class/泡面番" }, { "n": "奇幻", "v": "/class/奇幻" }, { "n": "战斗", "v": "/class/战斗" }, { "n": "日常", "v": "/class/日常" }, { "n": "后宫", "v": "/class/后宫" }, { "n": "百合", "v": "/class/百合" }, { "n": "治愈", "v": "/class/治愈" }, { "n": "校园", "v": "/class/校园" }, { "n": "恋爱", "v": "/class/恋爱" }, { "n": "游戏改", "v": "/class/游戏改" }, { "n": "轻改", "v": "/class/轻改" }, { "n": "青春", "v": "/class/青春" }, { "n": "催泪", "v": "/class/催泪" }, { "n": "音乐", "v": "/class/音乐" }, { "n": "偶像", "v": "/class/偶像" }, { "n": "悬疑", "v": "/class/悬疑" }, { "n": "GAL改", "v": "/class/GAL改" }, { "n": "科幻", "v": "/class/科幻" }, { "n": "推理", "v": "/class/推理" }, { "n": "萝莉", "v": "/class/萝莉" }, { "n": "热血", "v": "/class/热血" }, { "n": "猎奇", "v": "/class/猎奇" }, { "n": "冒险", "v": "/class/冒险" }, { "n": "励志", "v": "/class/励志" }, { "n": "机战", "v": "/class/机战" }, { "n": "致郁", "v": "/class/致郁" }, { "n": "剧情", "v": "/class/剧情" }] },
      { "key": "年份", "name": "年份", "value": [{ "n": "全部", "v": "" }, { "n": "2023", "v": "/year/2023" }, { "n": "2022", "v": "/year/2022" }, { "n": "2021", "v": "/year/2021" }, { "n": "2020", "v": "/year/2020" }, { "n": "2019", "v": "/year/2019" }, { "n": "2018", "v": "/year/2018" }, { "n": "2017", "v": "/year/2017" }, { "n": "2016", "v": "/year/2016" }, { "n": "2015", "v": "/year/2015" }, { "n": "2014", "v": "/year/2014" }, { "n": "2013", "v": "/year/2013" }, { "n": "2012", "v": "/year/2012" }, { "n": "2011", "v": "/year/2011" }, { "n": "2010", "v": "/year/2010" }] },
      { "key": "字母", "name": "字母", "value": [{ "n": "字母", "v": "" }, { "n": "A", "v": "/letter/A" }, { "n": "B", "v": "/letter/B" }, { "n": "C", "v": "/letter/C" }, { "n": "D", "v": "/letter/D" }, { "n": "E", "v": "/letter/E" }, { "n": "F", "v": "/letter/F" }, { "n": "G", "v": "/letter/G" }, { "n": "H", "v": "/letter/H" }, { "n": "I", "v": "/letter/I" }, { "n": "J", "v": "/letter/J" }, { "n": "K", "v": "/letter/K" }, { "n": "L", "v": "/letter/L" }, { "n": "M", "v": "/letter/M" }, { "n": "N", "v": "/letter/N" }, { "n": "O", "v": "/letter/O" }, { "n": "P", "v": "/letter/P" }, { "n": "Q", "v": "/letter/Q" }, { "n": "R", "v": "/letter/R" }, { "n": "S", "v": "/letter/S" }, { "n": "T", "v": "/letter/T" }, { "n": "U", "v": "/letter/U" }, { "n": "V", "v": "/letter/V" }, { "n": "W", "v": "/letter/W" }, { "n": "X", "v": "/letter/X" }, { "n": "Y", "v": "/letter/Y" }, { "n": "Z", "v": "/letter/Z" }, { "n": "0-9", "v": "/letter/0-9" }] },
      { "key": "排序", "name": "排序", "value": [{ "n": "时间排序", "v": "/by/time" }, { "n": "人气排序", "v": "/by/hits" }, { "n": "评分排序", "v": "/by/score" }] }],
    "23": [
      { "key": "分类", "name": "分类", "value": [{ "n": "全部", "v": "" }, { "n": "原创", "v": "/class/原创" }, { "n": "漫改", "v": "/class/漫改" }, { "n": "异世界", "v": "/class/异世界" }, { "n": "泡面番", "v": "/class/泡面番" }, { "n": "奇幻", "v": "/class/奇幻" }, { "n": "战斗", "v": "/class/战斗" }, { "n": "日常", "v": "/class/日常" }, { "n": "后宫", "v": "/class/后宫" }, { "n": "百合", "v": "/class/百合" }, { "n": "治愈", "v": "/class/治愈" }, { "n": "校园", "v": "/class/校园" }, { "n": "恋爱", "v": "/class/恋爱" }, { "n": "游戏改", "v": "/class/游戏改" }, { "n": "轻改", "v": "/class/轻改" }, { "n": "青春", "v": "/class/青春" }, { "n": "催泪", "v": "/class/催泪" }, { "n": "音乐", "v": "/class/音乐" }, { "n": "偶像", "v": "/class/偶像" }, { "n": "悬疑", "v": "/class/悬疑" }, { "n": "GAL改", "v": "/class/GAL改" }, { "n": "科幻", "v": "/class/科幻" }, { "n": "推理", "v": "/class/推理" }, { "n": "萝莉", "v": "/class/萝莉" }, { "n": "热血", "v": "/class/热血" }, { "n": "猎奇", "v": "/class/猎奇" }, { "n": "冒险", "v": "/class/冒险" }, { "n": "励志", "v": "/class/励志" }, { "n": "机战", "v": "/class/机战" }, { "n": "致郁", "v": "/class/致郁" }, { "n": "剧情", "v": "/class/剧情" }] },
      { "key": "年份", "name": "年份", "value": [{ "n": "全部", "v": "" }, { "n": "2023", "v": "/year/2023" }, { "n": "2022", "v": "/year/2022" }, { "n": "2021", "v": "/year/2021" }, { "n": "2020", "v": "/year/2020" }, { "n": "2019", "v": "/year/2019" }, { "n": "2018", "v": "/year/2018" }, { "n": "2017", "v": "/year/2017" }, { "n": "2016", "v": "/year/2016" }, { "n": "2015", "v": "/year/2015" }, { "n": "2014", "v": "/year/2014" }, { "n": "2013", "v": "/year/2013" }, { "n": "2012", "v": "/year/2012" }, { "n": "2011", "v": "/year/2011" }, { "n": "2010", "v": "/year/2010" }] },
      { "key": "字母", "name": "字母", "value": [{ "n": "字母", "v": "" }, { "n": "A", "v": "/letter/A" }, { "n": "B", "v": "/letter/B" }, { "n": "C", "v": "/letter/C" }, { "n": "D", "v": "/letter/D" }, { "n": "E", "v": "/letter/E" }, { "n": "F", "v": "/letter/F" }, { "n": "G", "v": "/letter/G" }, { "n": "H", "v": "/letter/H" }, { "n": "I", "v": "/letter/I" }, { "n": "J", "v": "/letter/J" }, { "n": "K", "v": "/letter/K" }, { "n": "L", "v": "/letter/L" }, { "n": "M", "v": "/letter/M" }, { "n": "N", "v": "/letter/N" }, { "n": "O", "v": "/letter/O" }, { "n": "P", "v": "/letter/P" }, { "n": "Q", "v": "/letter/Q" }, { "n": "R", "v": "/letter/R" }, { "n": "S", "v": "/letter/S" }, { "n": "T", "v": "/letter/T" }, { "n": "U", "v": "/letter/U" }, { "n": "V", "v": "/letter/V" }, { "n": "W", "v": "/letter/W" }, { "n": "X", "v": "/letter/X" }, { "n": "Y", "v": "/letter/Y" }, { "n": "Z", "v": "/letter/Z" }, { "n": "0-9", "v": "/letter/0-9" }] },
      { "key": "排序", "name": "排序", "value": [{ "n": "时间排序", "v": "/by/time" }, { "n": "人气排序", "v": "/by/hits" }, { "n": "评分排序", "v": "/by/score" }] }]
  },
  filter_url: '{{fl.排序}}{{fl.分类}}{{fl.字母}}/page/fypage{{fl.年份}}',
  cate_exclude: '求片留言',
  filterable: 1,
}