var rule = {
  title: '人人美剧[优]',
  host: 'https://rrmja.com/',
  class_name: '电影&剧集&综艺&动漫',
  class_url: '1&2&3&4',
  searchUrl: '/vodsearch/**----------fypage---.html',
  searchable: 2,
  quickSearch: 0,
  headers: {
    'User-Agent': 'PC_UA',
  },
  //url: '/vodshow/dyxlass-----------.html',
  url: '/vodtype/fyclass-fypage.html',
  filterable: 0,
  filter_url: '',
  filter_def:'',
  detailUrl: '/voddetail/fyid.html',
  play_parse: true,
  lazy: "js:\n  let html = request(input);\n  let hconf = html.match(/var player_.*?=(\\{.*?\\})\\s*</)[1];\n  let json = JSON5.parse(hconf);\n  let url = json.url;\n  if (json.encrypt == '1') {\n    url = unescape(url);\n  } else if (json.encrypt == '2') {\n    url = unescape(base64Decode(url));\n  } else if (json.encrypt == '3') {\n    url = url.replace('nanke_', '');\n    url = base64Decode(base64Decode(url));\n  }\n  if (/\\.(m3u8|mp4|m4a|mp3)/.test(url)) {\n    input = {\n      parse: 0,\n      jx: 0,\n      url: url,\n      headers: {'Referer': 'https://rrmja.com/'}\n    };\n  } else {\n    let iframeSrc = html.match(/<iframe[^>]+src=\"(https?:\\/\\/[^\"]+)\"/i);\n    if (iframeSrc) {\n      input = {\n        parse: 0,\n        jx: 1,\n        url: iframeSrc[1],\n        headers: {'Referer': 'https://rrmja.com/'}\n      };\n    } else {\n      input = url.startsWith('http') ? {parse:0,jx:1,url:url,headers:{'Referer': 'https://rrmja.com/'}} : input;\n    }\n  }",
  推荐: '.flex.wrap .public-list-box;a&&title;.public-list-div img&&data-src;.public-list-prb&&Text;a&&href',
  一级: '.flex.wrap .public-list-box;a&&title;.public-list-div img&&data-src;.public-list-prb&&Text;a&&href',
  二级: {
    title: '.this-desc-title&&Text;.this-desc-labels&&Text',
    img: '.this-pic-bj&&style',
    desc: '.this-desc-info&&Text;.this-desc-info span:eq(1)&&Text;.this-desc-info span:eq(2)&&Text;.this-info:eq(1)&&Text;.this-info:eq(0)&&Text;',
    content: '#height_limit&&Text',
    tabs: '.anthology-tab&&a',
    tab_text: 'body--span&&Text',
    lists: '.anthology-list-play:eq(#id)&&a',
    list_text: 'body&&Text',
    list_url: 'a&&href',
  },
  搜索: '.flex.wrap .public-list-box;.time-title&&Text;img&&data-src;.public-list-prb&&Text;a&&href',

}
