var rule = {
  title: '优质资源[资]',
  host: 'https://api.yzzy-api.com',
  homeTid: '13',
  homeUrl: '/inc/apijson.php?ac=detail&t={{rule.homeTid}}',
  detailUrl: '/inc/apijson.php?ac=detail&ids=fyid',
  searchUrl: 'https://api.yzzy-api.com/inc/apijson.php?ac=detail&wd=**&pg=fypage',
  url: '/inc/apijson.php?ac=detail&pg=fypage&t=fyclass',
  headers: {
    'User-Agent': 'MOBILE_UA',
  },
  timeout: 5000,
  class_parse: 'json:class;',
  limit: 20,
  multi: 1,
  searchable: 2,
  quickSearch: 1,
  filterable: 0,
  play_parse: true,
  parse_url: '',
  lazy: "js:\n  if (/\\.(m3u8|mp4)/.test(input)) {\n    input = { parse: 0, url: input };\n  } else {\n    if (rule.parse_url.startsWith('json:')) {\n      let purl = rule.parse_url.replace('json:', '') + input;\n      let html = request(purl);\n      let json = JSON.parse(html);\n      if (json.url) {\n        input = { parse: 0, url: json.url };\n      }\n    } else {\n      input = rule.parse_url + input;\n    }\n  }",
  推荐: '*',
  一级: 'json:list;vod_name;vod_pic;vod_remarks;vod_id;vod_play_from',
  二级: 'js:\n            let html=request(input);\n            html=JSON.parse(html);\n            let data=html.list;\n            VOD=data[0];',
  搜索: '*',
}