var rule = {
  模板:'mxpro',
  title: '唐僧影视',
  host: 'https://tsys888.com',
  url: '/index.php/vod/showfyfilter.html',
  searchUrl: '/index.php/vod/search/page/fypage/wd/**.html',
  tab_exclude: '排序',
  filterable: 1,
  filter: {
    "1": [{ "key": "类型", "name": "类型", "value": [{ "n": "全部", "v": "/id/1" }, { "n": "惊悚片", "v": "/id/20" }, { "n": "动画片", "v": "/id/23" }, { "n": "悬疑片", "v": "/id/24" }, { "n": "武侠片", "v": "/id/25" }, { "n": "奇幻片", "v": "/id/26" }, { "n": "喜剧片", "v": "/id/7" }, { "n": "动作片", "v": "/id/6" }, { "n": "爱情片", "v": "/id/8" }, { "n": "科幻片", "v": "/id/9" }, { "n": "恐怖片", "v": "/id/10" }, { "n": "剧情片", "v": "/id/11" }, { "n": "战争片", "v": "/id/12" }, { "n": "记录片", "v": "/id/27" }, { "n": "伦理片", "v": "/id/28" }, { "n": "其他片", "v": "/id/29" }, { "n": "犯罪片", "v": "/id/21" }, { "n": "冒险片", "v": "/id/22" }] }, { "key": "字母", "name": "字母", "value": [{ "n": "字母", "v": "" }, { "n": "A", "v": "/letter/A" }, { "n": "B", "v": "/letter/B" }, { "n": "C", "v": "/letter/C" }, { "n": "D", "v": "/letter/D" }, { "n": "E", "v": "/letter/E" }, { "n": "F", "v": "/letter/F" }, { "n": "G", "v": "/letter/G" }, { "n": "H", "v": "/letter/H" }, { "n": "I", "v": "/letter/I" }, { "n": "J", "v": "/letter/J" }, { "n": "K", "v": "/letter/K" }, { "n": "L", "v": "/letter/L" }, { "n": "M", "v": "/letter/M" }, { "n": "N", "v": "/letter/N" }, { "n": "O", "v": "/letter/O" }, { "n": "P", "v": "/letter/P" }, { "n": "Q", "v": "/letter/Q" }, { "n": "R", "v": "/letter/R" }, { "n": "S", "v": "/letter/S" }, { "n": "T", "v": "/letter/T" }, { "n": "U", "v": "/letter/U" }, { "n": "V", "v": "/letter/V" }, { "n": "W", "v": "/letter/W" }, { "n": "X", "v": "/letter/X" }, { "n": "Y", "v": "/letter/Y" }, { "n": "Z", "v": "/letter/Z" }, { "n": "0-9", "v": "/letter/0-9" }] }, { "key": "排序", "name": "排序", "value": [{ "n": "时间排序", "v": "/by/time" }, { "n": "人气排序", "v": "/by/hits" }, { "n": "评分排序", "v": "/by/score" }] }],
    "2": [{ "key": "类型", "name": "类型", "value": [{ "n": "全部", "v": "/id/2" }, { "n": "国产剧", "v": "/id/13" }, { "n": "香港剧", "v": "/id/31" }, { "n": "欧美剧", "v": "/id/32" }, { "n": "其他剧", "v": "/id/33" }, { "n": "台湾剧", "v": "/id/14" }, { "n": "韩国剧", "v": "/id/15" }, { "n": "泰国剧", "v": "/id/16" }, { "n": "海外剧", "v": "/id/47" }, { "n": "日本剧", "v": "/id/30" }] }, { "key": "字母", "name": "字母", "value": [{ "n": "字母", "v": "" }, { "n": "A", "v": "/letter/A" }, { "n": "B", "v": "/letter/B" }, { "n": "C", "v": "/letter/C" }, { "n": "D", "v": "/letter/D" }, { "n": "E", "v": "/letter/E" }, { "n": "F", "v": "/letter/F" }, { "n": "G", "v": "/letter/G" }, { "n": "H", "v": "/letter/H" }, { "n": "I", "v": "/letter/I" }, { "n": "J", "v": "/letter/J" }, { "n": "K", "v": "/letter/K" }, { "n": "L", "v": "/letter/L" }, { "n": "M", "v": "/letter/M" }, { "n": "N", "v": "/letter/N" }, { "n": "O", "v": "/letter/O" }, { "n": "P", "v": "/letter/P" }, { "n": "Q", "v": "/letter/Q" }, { "n": "R", "v": "/letter/R" }, { "n": "S", "v": "/letter/S" }, { "n": "T", "v": "/letter/T" }, { "n": "U", "v": "/letter/U" }, { "n": "V", "v": "/letter/V" }, { "n": "W", "v": "/letter/W" }, { "n": "X", "v": "/letter/X" }, { "n": "Y", "v": "/letter/Y" }, { "n": "Z", "v": "/letter/Z" }, { "n": "0-9", "v": "/letter/0-9" }] }, { "key": "排序", "name": "排序", "value": [{ "n": "时间排序", "v": "/by/time" }, { "n": "人气排序", "v": "/by/hits" }, { "n": "评分排序", "v": "/by/score" }] }],
    "5": [{ "key": "字母", "name": "字母", "value": [{ "n": "字母", "v": "" }, { "n": "A", "v": "/letter/A" }, { "n": "B", "v": "/letter/B" }, { "n": "C", "v": "/letter/C" }, { "n": "D", "v": "/letter/D" }, { "n": "E", "v": "/letter/E" }, { "n": "F", "v": "/letter/F" }, { "n": "G", "v": "/letter/G" }, { "n": "H", "v": "/letter/H" }, { "n": "I", "v": "/letter/I" }, { "n": "J", "v": "/letter/J" }, { "n": "K", "v": "/letter/K" }, { "n": "L", "v": "/letter/L" }, { "n": "M", "v": "/letter/M" }, { "n": "N", "v": "/letter/N" }, { "n": "O", "v": "/letter/O" }, { "n": "P", "v": "/letter/P" }, { "n": "Q", "v": "/letter/Q" }, { "n": "R", "v": "/letter/R" }, { "n": "S", "v": "/letter/S" }, { "n": "T", "v": "/letter/T" }, { "n": "U", "v": "/letter/U" }, { "n": "V", "v": "/letter/V" }, { "n": "W", "v": "/letter/W" }, { "n": "X", "v": "/letter/X" }, { "n": "Y", "v": "/letter/Y" }, { "n": "Z", "v": "/letter/Z" }, { "n": "0-9", "v": "/letter/0-9" }] }, { "key": "排序", "name": "排序", "value": [{ "n": "时间排序", "v": "/by/time" }, { "n": "人气排序", "v": "/by/hits" }, { "n": "评分排序", "v": "/by/score" }] }],
    "55": [{ "key": "类型", "name": "类型", "value": [{ "n": "全部", "v": "/id/55" }, { "n": "大陆综艺", "v": "/id/56" }, { "n": "台湾综艺", "v": "/id/57" }, { "n": "韩国综艺", "v": "/id/58" }, { "n": "日本综艺", "v": "/id/59" }, { "n": "欧美综艺", "v": "/id/60" }, { "n": "香港综艺", "v": "/id/61" }, { "n": "其他综艺", "v": "/id/62" }] }, { "key": "字母", "name": "字母", "value": [{ "n": "字母", "v": "" }, { "n": "A", "v": "/letter/A" }, { "n": "B", "v": "/letter/B" }, { "n": "C", "v": "/letter/C" }, { "n": "D", "v": "/letter/D" }, { "n": "E", "v": "/letter/E" }, { "n": "F", "v": "/letter/F" }, { "n": "G", "v": "/letter/G" }, { "n": "H", "v": "/letter/H" }, { "n": "I", "v": "/letter/I" }, { "n": "J", "v": "/letter/J" }, { "n": "K", "v": "/letter/K" }, { "n": "L", "v": "/letter/L" }, { "n": "M", "v": "/letter/M" }, { "n": "N", "v": "/letter/N" }, { "n": "O", "v": "/letter/O" }, { "n": "P", "v": "/letter/P" }, { "n": "Q", "v": "/letter/Q" }, { "n": "R", "v": "/letter/R" }, { "n": "S", "v": "/letter/S" }, { "n": "T", "v": "/letter/T" }, { "n": "U", "v": "/letter/U" }, { "n": "V", "v": "/letter/V" }, { "n": "W", "v": "/letter/W" }, { "n": "X", "v": "/letter/X" }, { "n": "Y", "v": "/letter/Y" }, { "n": "Z", "v": "/letter/Z" }, { "n": "0-9", "v": "/letter/0-9" }] }, { "key": "排序", "name": "排序", "value": [{ "n": "时间排序", "v": "/by/time" }, { "n": "人气排序", "v": "/by/hits" }, { "n": "评分排序", "v": "/by/score" }] }],
    "63": [{ "key": "类型", "name": "类型", "value": [{ "n": "全部", "v": "/id/63" }, { "n": "国产动漫", "v": "/id/64" }, { "n": "欧美动漫", "v": "/id/65" }, { "n": "日本动漫", "v": "/id/66" }, { "n": "其他动漫", "v": "/id/67" }] }, { "key": "字母", "name": "字母", "value": [{ "n": "字母", "v": "" }, { "n": "A", "v": "/letter/A" }, { "n": "B", "v": "/letter/B" }, { "n": "C", "v": "/letter/C" }, { "n": "D", "v": "/letter/D" }, { "n": "E", "v": "/letter/E" }, { "n": "F", "v": "/letter/F" }, { "n": "G", "v": "/letter/G" }, { "n": "H", "v": "/letter/H" }, { "n": "I", "v": "/letter/I" }, { "n": "J", "v": "/letter/J" }, { "n": "K", "v": "/letter/K" }, { "n": "L", "v": "/letter/L" }, { "n": "M", "v": "/letter/M" }, { "n": "N", "v": "/letter/N" }, { "n": "O", "v": "/letter/O" }, { "n": "P", "v": "/letter/P" }, { "n": "Q", "v": "/letter/Q" }, { "n": "R", "v": "/letter/R" }, { "n": "S", "v": "/letter/S" }, { "n": "T", "v": "/letter/T" }, { "n": "U", "v": "/letter/U" }, { "n": "V", "v": "/letter/V" }, { "n": "W", "v": "/letter/W" }, { "n": "X", "v": "/letter/X" }, { "n": "Y", "v": "/letter/Y" }, { "n": "Z", "v": "/letter/Z" }, { "n": "0-9", "v": "/letter/0-9" }] }, { "key": "排序", "name": "排序", "value": [{ "n": "时间排序", "v": "/by/time" }, { "n": "人气排序", "v": "/by/hits" }, { "n": "评分排序", "v": "/by/score" }] }]
  },
  filter_url: '{{fl.排序}}{{fl.类型}}{{fl.字母}}/page/fypage',
  filter_def: { '1': { 类型: '/id/1' }, '2': { 类型: '/id/2' }, '5': { 类型: '/id/5' }, '55': { 类型: '/id/55' }, '63': { 类型: '/id/63' } },
}