var rule = {
  类型:'影视',//影视|听书|漫画|小说
  title:'多多DJ[音]',
  host:'http://www.duoduodj.com',
  url:'/djlist/fyclass_fypage.html',
  searchUrl:'/s/sok**_fypage.html',
  searchable:2,
  quickSearch:0,
  filterable:0,
  headers:{
      'User-Agent':'MOBILE_UA',
  },
  timeout:5000,
  class_parse:'.nav li:gt(2):lt(11);a&&Text;a&&href;.*/(\\d+)',
  cate_exclude:'',
  play_parse:true,
  lazy:'',
  double:true,
  推荐:'.list li;li;font&&Text;.lazy&&src;aside&&Text;a:eq(1)&&href',
  一级:'.news-list li;font&&Text;.lazy&&src;aside&&Text;a:eq(1)&&href',
  /*二级:{
    title:'.lazy&&alt;vod_type',
    img:'td img&&src',
    desc:'主要信息;年代;地区;演员;导演',
    content:'简介',
    tabs:'',
    lists:'xx:eq(#id)&&a',
    tab_text:'body&&Text',
    list_text:'body&&Text',
    list_url:'a&&href',
    list_url_prefix: '',
  },*/
  二级:'*',
  搜索:'*',
}