var rule = {
   模板: 'mxone5',
   title: '我播',
   host: 'https://www.wobotv.cc',
   class_parse: '.drop-content-items li:lt(7);a&&Text;a&&href;type/(.*?)/',
   url: '/show/fyfilter/',
   searchUrl: '/search/**--/page/fypage/',
   搜索: '.module-items .module-search-item;a&&title;img&&data-src;.video-serial&&Text;.video-serial&&href',
   filter: {
      "dianying": [{ key: '类型', name: '类型', value: [{ n: '全部类型', v: '1', }, { n: '动作片', v: 'dongzuopian', }, { n: '喜剧片', v: 'xijupian', }, { n: '爱情片', v: 'aiqingpian', }, { n: '科幻片', v: 'kehuanpian', }, { n: '恐怖片', v: 'kongbupian', }, { n: '剧情片', v: 'juqingpian', }, { n: '战争片', v: 'zhanzhengpian', }, { n: '动画片', v: 'donghuapian', },], }, { key: '地区', name: '地区', value: [{ n: '全部地区', v: '', }, { n: '大陆', v: '/area/大陆', }, { n: '香港', v: '/area/香港', }, { n: '台湾', v: '/area/台湾', }, { n: '韩国', v: '/area/韩国', }, { n: '日本', v: '/area/日本', }, { n: '美国', v: '/area/美国', }, { n: '法国', v: '/area/法国', }, { n: '英国', v: '/area/英国', }, { n: '泰国', v: '/area/泰国', }, { n: '印度', v: '/area/印度', }, { n: '新加坡', v: '/area/新加坡', }, { n: '其它', v: '/area/其它', },], }, { key: '语言', name: '语言', value: [{ n: '全部语言', v: '', }, { n: '国语', v: '/lang/国语', }, { n: '粤语', v: '/lang/粤语', }, { n: '闽南语', v: '/lang/闽南语', }, { n: '韩语', v: '/lang/韩语', }, { n: '日语', v: '/lang/日语', }, { n: '英语', v: '/lang/英语', }, { n: '其它', v: '/lang/其它', },], }, { key: '年代', name: '年代', value: [{ n: '全部时间', v: '', }, { n: '2025', v: '/year/2025', }, { n: '2024', v: '/year/2024', }, { n: '2023', v: '/year/2023', }, { n: '2022', v: '/year/2022', }, { n: '2021', v: '/year/2021', }, { n: '2020', v: '/year/2020', }, { n: '2019', v: '/year/2019', }, { n: '2018', v: '/year/2018', }, { n: '2017', v: '/year/2017', }, { n: '2016', v: '/year/2016', }, { n: '2015', v: '/year/2015', }, { n: '2014', v: '/year/2014', }, { n: '2013', v: '/year/2013', }, { n: '2012', v: '/year/2012', }, { n: '2011', v: '/year/2011', }, { n: '2010', v: '/year/2010', }, { n: '2009-2000', v: '/year/2009-2000', }, { n: '1999-1990', v: '/year/1999-1990', }, { n: '1989-1980', v: '/year/1989-1980', }, { n: '1979-1900', v: '/year/1979-1900', },], }, { key: '字母', name: '字母', value: [{ n: '字母查找', v: '', }, { n: 'A', v: '/letter/A', }, { n: 'B', v: '/letter/B', }, { n: 'C', v: '/letter/C', }, { n: 'D', v: '/letter/D', }, { n: 'E', v: '/letter/E', }, { n: 'F', v: '/letter/F', }, { n: 'G', v: '/letter/G', }, { n: 'H', v: '/letter/H', }, { n: 'I', v: '/letter/I', }, { n: 'J', v: '/letter/J', }, { n: 'K', v: '/letter/K', }, { n: 'L', v: '/letter/L', }, { n: 'M', v: '/letter/M', }, { n: 'N', v: '/letter/N', }, { n: 'O', v: '/letter/O', }, { n: 'P', v: '/letter/P', }, { n: 'Q', v: '/letter/Q', }, { n: 'R', v: '/letter/R', }, { n: 'S', v: '/letter/S', }, { n: 'T', v: '/letter/T', }, { n: 'U', v: '/letter/U', }, { n: 'V', v: '/letter/V', }, { n: 'W', v: '/letter/W', }, { n: 'X', v: '/letter/X', }, { n: 'Y', v: '/letter/Y', }, { n: 'Z', v: '/letter/Z', }, { n: '0-9', v: '/letter/0-9', },], }, { key: '排序', name: '排序', value: [{ n: '时间排序', v: '/by/time', }, { n: '人气排序', v: '/by/hits', },], },],
      "dianshiju": [{ key: '类型', name: '类型', value: [{ n: '全部类型', v: '2', }, { n: '国产剧', v: 'guochanju', }, { n: '香港剧', v: 'xianggangju', }, { n: '韩国剧', v: 'hanguoju', }, { n: '欧美剧', v: 'oumeiju', }, { n: '台湾剧', v: 'taiwanju', }, { n: '日本剧', v: 'ribenju', }, { n: '泰国剧', v: 'taiguoju', }, { n: '海外剧', v: 'haiwaiju', },], }, { key: '地区', name: '地区', value: [{ n: '全部地区', v: '', }, { n: '大陆', v: '/area/大陆', }, { n: '香港', v: '/area/香港', }, { n: '台湾', v: '/area/台湾', }, { n: '韩国', v: '/area/韩国', }, { n: '日本', v: '/area/日本', }, { n: '美国', v: '/area/美国', }, { n: '法国', v: '/area/法国', }, { n: '英国', v: '/area/英国', }, { n: '泰国', v: '/area/泰国', }, { n: '印度', v: '/area/印度', }, { n: '其它', v: '/area/其它', },], }, { key: '语言', name: '语言', value: [{ n: '全部语言', v: '', }, { n: '国语', v: '/lang/国语', }, { n: '粤语', v: '/lang/粤语', }, { n: '闽南语', v: '/lang/闽南语', }, { n: '韩语', v: '/lang/韩语', }, { n: '日语', v: '/lang/日语', }, { n: '英语', v: '/lang/英语', }, { n: '其它', v: '/lang/其它', },], }, { key: '年代', name: '年代', value: [{ n: '全部时间', v: '', }, { n: '2025', v: '/year/2025', }, { n: '2024', v: '/year/2024', }, { n: '2023', v: '/year/2023', }, { n: '2022', v: '/year/2022', }, { n: '2021', v: '/year/2021', }, { n: '2020', v: '/year/2020', }, { n: '2019', v: '/year/2019', }, { n: '2018', v: '/year/2018', }, { n: '2017', v: '/year/2017', }, { n: '2016', v: '/year/2016', }, { n: '2015', v: '/year/2015', }, { n: '2014', v: '/year/2014', }, { n: '2013', v: '/year/2013', }, { n: '2012', v: '/year/2012', }, { n: '2011', v: '/year/2011', }, { n: '2010', v: '/year/2010', }, { n: '2009-2000', v: '/year/2009-2000', }, { n: '1999-1990', v: '/year/1999-1990', }, { n: '1989-1980', v: '/year/1989-1980', }, { n: '1979-1900', v: '/year/1979-1900', },], }, { key: '字母', name: '字母', value: [{ n: '字母查找', v: '', }, { n: 'A', v: '/letter/A', }, { n: 'B', v: '/letter/B', }, { n: 'C', v: '/letter/C', }, { n: 'D', v: '/letter/D', }, { n: 'E', v: '/letter/E', }, { n: 'F', v: '/letter/F', }, { n: 'G', v: '/letter/G', }, { n: 'H', v: '/letter/H', }, { n: 'I', v: '/letter/I', }, { n: 'J', v: '/letter/J', }, { n: 'K', v: '/letter/K', }, { n: 'L', v: '/letter/L', }, { n: 'M', v: '/letter/M', }, { n: 'N', v: '/letter/N', }, { n: 'O', v: '/letter/O', }, { n: 'P', v: '/letter/P', }, { n: 'Q', v: '/letter/Q', }, { n: 'R', v: '/letter/R', }, { n: 'S', v: '/letter/S', }, { n: 'T', v: '/letter/T', }, { n: 'U', v: '/letter/U', }, { n: 'V', v: '/letter/V', }, { n: 'W', v: '/letter/W', }, { n: 'X', v: '/letter/X', }, { n: 'Y', v: '/letter/Y', }, { n: 'Z', v: '/letter/Z', }, { n: '0-9', v: '/letter/0-9', },], }, { key: '排序', name: '排序', value: [{ n: '时间排序', v: '/by/time', }, { n: '人气排序', v: '/by/hits', },], },],
      "dongman": [{ key: '地区', name: '地区', value: [{ n: '全部地区', v: '', }, { n: '大陆', v: '/area/大陆', }, { n: '台湾', v: '/area/台湾', }, { n: '香港', v: '/area/香港', }, { n: '韩国', v: '/area/韩国', }, { n: '日本', v: '/area/日本', }, { n: '美国', v: '/area/美国', }, { n: '其它', v: '/area/其它', },], }, { key: '语言', name: '语言', value: [{ n: '全部语言', v: '', }, { n: '国语', v: '/lang/国语', }, { n: '粤语', v: '/lang/粤语', }, { n: '闽南语', v: '/lang/闽南语', }, { n: '日语', v: '/lang/日语', }, { n: '韩语', v: '/lang/韩语', }, { n: '英语', v: '/lang/英语', }, { n: '其它', v: '/lang/其它', },], }, { key: '年代', name: '年代', value: [{ n: '全部时间', v: '', }, { n: '2025', v: '/year/2025', }, { n: '2024', v: '/year/2024', }, { n: '2023', v: '/year/2023', }, { n: '2022', v: '/year/2022', }, { n: '2021', v: '/year/2021', }, { n: '2020', v: '/year/2020', }, { n: '2019', v: '/year/2019', }, { n: '2018', v: '/year/2018', }, { n: '2017', v: '/year/2017', }, { n: '2016', v: '/year/2016', }, { n: '2015', v: '/year/2015', }, { n: '2014', v: '/year/2014', }, { n: '2013', v: '/year/2013', }, { n: '2012', v: '/year/2012', }, { n: '2011', v: '/year/2011', }, { n: '2010', v: '/year/2010', }, { n: '2009-2000', v: '/year/2009-2000', }, { n: '1999-1990', v: '/year/1999-1990', }, { n: '1989-1980', v: '/year/1989-1980', }, { n: '1979-1900', v: '/year/1979-1900', },], }, { key: '字母', name: '字母', value: [{ n: '字母查找', v: '', }, { n: 'A', v: '/letter/A', }, { n: 'B', v: '/letter/B', }, { n: 'C', v: '/letter/C', }, { n: 'D', v: '/letter/D', }, { n: 'E', v: '/letter/E', }, { n: 'F', v: '/letter/F', }, { n: 'G', v: '/letter/G', }, { n: 'H', v: '/letter/H', }, { n: 'I', v: '/letter/I', }, { n: 'J', v: '/letter/J', }, { n: 'K', v: '/letter/K', }, { n: 'L', v: '/letter/L', }, { n: 'M', v: '/letter/M', }, { n: 'N', v: '/letter/N', }, { n: 'O', v: '/letter/O', }, { n: 'P', v: '/letter/P', }, { n: 'Q', v: '/letter/Q', }, { n: 'R', v: '/letter/R', }, { n: 'S', v: '/letter/S', }, { n: 'T', v: '/letter/T', }, { n: 'U', v: '/letter/U', }, { n: 'V', v: '/letter/V', }, { n: 'W', v: '/letter/W', }, { n: 'X', v: '/letter/X', }, { n: 'Y', v: '/letter/Y', }, { n: 'Z', v: '/letter/Z', }, { n: '0-9', v: '/letter/0-9', },], }, { key: '排序', name: '排序', value: [{ n: '时间排序', v: '/by/time', }, { n: '人气排序', v: '/by/hits', },], },],
   },
   filter_url: '{{fl.类型}}{{fl.地区}}{{fl.排序}}{{fl.字母}}/page/fypage{{fl.年代}}',
   filter_def: { 'dianying': { 类型: 'dianying' }, 'dianshiju': { 类型: 'dianshiju' }, 'dongman': { 类型: 'dongman' } },
   filterable: 1,
}