var rule = {
   类型: '影视',//影视|听书|漫画|小说
   title: '热片网',
   host: 'http://www.repian.cc',
   url: '/fyfilter.html',
   searchUrl: '/vod-search-wd-**-pagefypage.html',
   searchable: 2,
   quickSearch: 0,
   filterable: 1,
   filter: {
      "dianshiju/listindex2": [{ "key": "分类", "name": "分类", "value": [{ "n": "全部", "v": "dianshiju/listindex2" }, { "n": "大陆剧", "v": "guochanju/listindex15" }, { "n": "港台剧", "v": "gangtaiju/listindex16" }, { "n": "欧美剧", "v": "oumeiju/listindex17" }, { "n": "日韩剧", "v": "rihanju/listindex18" }, { "n": "海外剧", "v": "taiguoju/listindex19" }] }, { "key": "年份", "name": "年份", "value": [{ "n": "全部", "v": "" }, { "n": "2023", "v": "2023" }, { "n": "2022", "v": "2022" }, { "n": "2021", "v": "2021" }, { "n": "2020", "v": "2020" }, { "n": "2019", "v": "2019" }, { "n": "2018", "v": "2018" }, { "n": "2017", "v": "2017" }, { "n": "2016", "v": "2016" }, { "n": "1999-2009", "v": "1999,2009" }, { "n": "90年代", "v": "1990,1999" }, { "n": "80年代", "v": "1980,1989" }, { "n": "更早", "v": "1900,1980" }] }, { "key": "地区", "name": "地区", "value": [{ "n": "全部", "v": "" }, { "n": "大陆", "v": "dalu" }, { "n": "美国", "v": "meiguo" }, { "n": "香港", "v": "xianggang" }, { "n": "台湾", "v": "taiwan" }, { "n": "韩国", "v": "hanguo" }, { "n": "日本", "v": "riben" }, { "n": "泰国", "v": "taiguo" }, { "n": "新加坡", "v": "xinjiapo" }, { "n": "马来西亚", "v": "malaixiya" }, { "n": "印度", "v": "yindu" }, { "n": "英国", "v": "yingguo" }, { "n": "法国", "v": "faguo" }, { "n": "加拿大", "v": "jianada" }] }, { "key": "字母", "name": "字母", "value": [{ "n": "全部", "v": "" }, { "n": "A", "v": "A" }, { "n": "B", "v": "B" }, { "n": "C", "v": "C" }, { "n": "D", "v": "D" }, { "n": "E", "v": "E" }, { "n": "F", "v": "F" }, { "n": "G", "v": "G" }, { "n": "H", "v": "H" }, { "n": "I", "v": "I" }, { "n": "J", "v": "J" }, { "n": "K", "v": "K" }, { "n": "L", "v": "L" }, { "n": "M", "v": "M" }, { "n": "N", "v": "N" }, { "n": "O", "v": "O" }, { "n": "P", "v": "P" }, { "n": "Q", "v": "Q" }, { "n": "R", "v": "R" }, { "n": "S", "v": "S" }, { "n": "T", "v": "T" }, { "n": "U", "v": "U" }, { "n": "V", "v": "V" }, { "n": "W", "v": "W" }, { "n": "X", "v": "X" }, { "n": "Y", "v": "Y" }, { "n": "Z", "v": "Z" }, { "n": "0-9", "v": "0,1,2,3,4,5,6,7,8,9" }] }, { "key": "排序", "name": "排序", "value": [{ "n": "按时间", "v": "addtime" }, { "n": "按人气", "v": "hits" }, { "n": "按评分", "v": "gold" }] }],
      "dianying/listindex1": [{ "key": "分类", "name": "分类", "value": [{ "n": "全部", "v": "dianying/listindex1" }, { "n": "动作片", "v": "dongzuopian/listindex8" }, { "n": "喜剧片", "v": "xijupian/listindex9" }, { "n": "爱情片", "v": "aiqingpian/listindex10" }, { "n": "科幻片", "v": "kehuanpian/listindex11" }, { "n": "恐怖片", "v": "kongbupian/listindex12" }, { "n": "战争片", "v": "zhanzhengpian/listindex13" }, { "n": "剧情片", "v": "gushipian/listindex14" }] }, { "key": "年份", "name": "年份", "value": [{ "n": "全部", "v": "" }, { "n": "2023", "v": "2023" }, { "n": "2022", "v": "2022" }, { "n": "2021", "v": "2021" }, { "n": "2020", "v": "2020" }, { "n": "2019", "v": "2019" }, { "n": "2018", "v": "2018" }, { "n": "2017", "v": "2017" }, { "n": "2016", "v": "2016" }, { "n": "1999-2009", "v": "1999,2009" }, { "n": "90年代", "v": "1990,1999" }, { "n": "80年代", "v": "1980,1989" }, { "n": "更早", "v": "1900,1980" }] }, { "key": "字母", "name": "字母", "value": [{ "n": "全部", "v": "" }, { "n": "A", "v": "A" }, { "n": "B", "v": "B" }, { "n": "C", "v": "C" }, { "n": "D", "v": "D" }, { "n": "E", "v": "E" }, { "n": "F", "v": "F" }, { "n": "G", "v": "G" }, { "n": "H", "v": "H" }, { "n": "I", "v": "I" }, { "n": "J", "v": "J" }, { "n": "K", "v": "K" }, { "n": "L", "v": "L" }, { "n": "M", "v": "M" }, { "n": "N", "v": "N" }, { "n": "O", "v": "O" }, { "n": "P", "v": "P" }, { "n": "Q", "v": "Q" }, { "n": "R", "v": "R" }, { "n": "S", "v": "S" }, { "n": "T", "v": "T" }, { "n": "U", "v": "U" }, { "n": "V", "v": "V" }, { "n": "W", "v": "W" }, { "n": "X", "v": "X" }, { "n": "Y", "v": "Y" }, { "n": "Z", "v": "Z" }, { "n": "0-9", "v": "0,1,2,3,4,5,6,7,8,9" }] }, { "key": "排序", "name": "排序", "value": [{ "n": "按时间", "v": "addtime" }, { "n": "按人气", "v": "hits" }, { "n": "按评分", "v": "gold" }] }],
      "dongman/listindex3": [{ "key": "分类", "name": "分类", "value": [{ "n": "全部", "v": "dongman/listindex3" }] }, { "key": "年份", "name": "年份", "value": [{ "n": "全部", "v": "" }, { "n": "2023", "v": "2023" }, { "n": "2022", "v": "2022" }, { "n": "2021", "v": "2021" }, { "n": "2020", "v": "2020" }, { "n": "2019", "v": "2019" }, { "n": "2018", "v": "2018" }, { "n": "2017", "v": "2017" }, { "n": "2016", "v": "2016" }, { "n": "1999-2009", "v": "1999,2009" }, { "n": "90年代", "v": "1990,1999" }, { "n": "80年代", "v": "1980,1989" }, { "n": "更早", "v": "1900,1980" }] }, { "key": "地区", "name": "地区", "value": [{ "n": "全部", "v": "" }, { "n": "大陆", "v": "dalu" }, { "n": "美国", "v": "meiguo" }, { "n": "香港", "v": "xianggang" }, { "n": "台湾", "v": "taiwan" }, { "n": "韩国", "v": "hanguo" }, { "n": "日本", "v": "riben" }, { "n": "泰国", "v": "taiguo" }, { "n": "新加坡", "v": "xinjiapo" }, { "n": "马来西亚", "v": "malaixiya" }, { "n": "印度", "v": "yindu" }, { "n": "英国", "v": "yingguo" }, { "n": "法国", "v": "faguo" }, { "n": "加拿大", "v": "jianada" }] }, { "key": "字母", "name": "字母", "value": [{ "n": "全部", "v": "" }, { "n": "A", "v": "A" }, { "n": "B", "v": "B" }, { "n": "C", "v": "C" }, { "n": "D", "v": "D" }, { "n": "E", "v": "E" }, { "n": "F", "v": "F" }, { "n": "G", "v": "G" }, { "n": "H", "v": "H" }, { "n": "I", "v": "I" }, { "n": "J", "v": "J" }, { "n": "K", "v": "K" }, { "n": "L", "v": "L" }, { "n": "M", "v": "M" }, { "n": "N", "v": "N" }, { "n": "O", "v": "O" }, { "n": "P", "v": "P" }, { "n": "Q", "v": "Q" }, { "n": "R", "v": "R" }, { "n": "S", "v": "S" }, { "n": "T", "v": "T" }, { "n": "U", "v": "U" }, { "n": "V", "v": "V" }, { "n": "W", "v": "W" }, { "n": "X", "v": "X" }, { "n": "Y", "v": "Y" }, { "n": "Z", "v": "Z" }, { "n": "0-9", "v": "0,1,2,3,4,5,6,7,8,9" }] }, { "key": "排序", "name": "排序", "value": [{ "n": "按时间", "v": "addtime" }, { "n": "按人气", "v": "hits" }, { "n": "按评分", "v": "gold" }] }],
      "zongyi/listindex4": [{ "key": "分类", "name": "分类", "value": [{ "n": "全部", "v": "zongyi/listindex4" }] }, { "key": "年份", "name": "年份", "value": [{ "n": "全部", "v": "" }, { "n": "2023", "v": "2023" }, { "n": "2022", "v": "2022" }, { "n": "2021", "v": "2021" }, { "n": "2020", "v": "2020" }, { "n": "2019", "v": "2019" }, { "n": "2018", "v": "2018" }, { "n": "2017", "v": "2017" }, { "n": "2016", "v": "2016" }, { "n": "1999-2009", "v": "1999,2009" }, { "n": "90年代", "v": "1990,1999" }, { "n": "80年代", "v": "1980,1989" }, { "n": "更早", "v": "1900,1980" }] }, { "key": "地区", "name": "地区", "value": [{ "n": "全部", "v": "" }, { "n": "大陆", "v": "dalu" }, { "n": "美国", "v": "meiguo" }, { "n": "香港", "v": "xianggang" }, { "n": "台湾", "v": "taiwan" }, { "n": "韩国", "v": "hanguo" }, { "n": "日本", "v": "riben" }, { "n": "泰国", "v": "taiguo" }, { "n": "新加坡", "v": "xinjiapo" }, { "n": "马来西亚", "v": "malaixiya" }, { "n": "印度", "v": "yindu" }, { "n": "英国", "v": "yingguo" }, { "n": "法国", "v": "faguo" }, { "n": "加拿大", "v": "jianada" }] }, { "key": "字母", "name": "字母", "value": [{ "n": "全部", "v": "" }, { "n": "A", "v": "A" }, { "n": "B", "v": "B" }, { "n": "C", "v": "C" }, { "n": "D", "v": "D" }, { "n": "E", "v": "E" }, { "n": "F", "v": "F" }, { "n": "G", "v": "G" }, { "n": "H", "v": "H" }, { "n": "I", "v": "I" }, { "n": "J", "v": "J" }, { "n": "K", "v": "K" }, { "n": "L", "v": "L" }, { "n": "M", "v": "M" }, { "n": "N", "v": "N" }, { "n": "O", "v": "O" }, { "n": "P", "v": "P" }, { "n": "Q", "v": "Q" }, { "n": "R", "v": "R" }, { "n": "S", "v": "S" }, { "n": "T", "v": "T" }, { "n": "U", "v": "U" }, { "n": "V", "v": "V" }, { "n": "W", "v": "W" }, { "n": "X", "v": "X" }, { "n": "Y", "v": "Y" }, { "n": "Z", "v": "Z" }, { "n": "0-9", "v": "0,1,2,3,4,5,6,7,8,9" }] }, { "key": "排序", "name": "排序", "value": [{ "n": "按时间", "v": "addtime" }, { "n": "按人气", "v": "hits" }, { "n": "按评分", "v": "gold" }] }]
   },
   filter_url: '{{fl.分类}}-type--{{fl.年份}}-{{fl.字母}}-{{fl.排序}}-{{fl.地区}}--pagefypage',
   filter_def: { 'dianshiju/listindex2': { 分类: 'dianshiju/listindex2' }, 'dianying/listindex1': { 分类: 'dianying/listindex1' }, 'dongman/listindex3': { 分类: 'dongman/listindex3' }, 'zongyi/listindex4': { 分类: 'zongyi/listindex4' } },
   headers: {
      'Accept-Language': 'zh-CN',
      'User-Agent': 'PC_UA',
   },
   timeout: 5000,
   //class_parse: '.navbar-nav li:gt(0):lt(5);a&&Text;a&&href;cc\/(.*?)-page1\.html',
   class_name:'电视剧&电影&动漫&综艺',
   class_url:'dianshiju/listindex2&dianying/listindex1&dongman/listindex3&zongyi/listindex4',
   cate_exclude: '',
   play_parse: true,
   lazy: $js.toString(() => {
      input = { parse: 1, url: input, js: '' };
   }),
   double: true,
   推荐: '.col-md-2;li;*;*;*;*;*',
   一级: '.box-video-list&&ul&&li;a&&title;a&&data-original;.note&&Text;a&&href;.subtitle&&Text',
   二级: {
      title: 'h1--em&&Text;ul.info&&li:eq(2)&&Text',
      img: '.video-pic&&style',
      desc: 'ul.info&&li:eq(10)&&Text;ul.info&&li:eq(4)&&Text;ul.info&&li:eq(6)&&Text;ul.info&&li:eq(3)&&Text;ul.info&&li:eq(5)&&Text',
      content: '.details-content-all&&Text',
      tabs: '.dropdown-menu:eq(-1)&&li',
      lists: 'div.playlist&&ul:eq(#id)&&li',
      tab_text: 'body&&Text',
      list_text: 'body&&Text',
      list_url: 'a&&href',
      list_url_prefix: '',
   },
   搜索: '#content&&.details-info-min;*;*;ul.info&&li:eq(2)&&Text;*;.details-content-default&&Text',
}