var rule = {
    title: '看剧网',
    host: 'https://www.kanjuw.net',
    url: '/search.php?fyfilter',
    searchUrl: '/search.php?page=fypage&searchword=**&searchtype=',
    searchable: 2,
    quickSearch: 0,
    filterable: 1,
    headers: {
        'User-Agent': 'PC_UA',
    },
    class_name: '电影&剧集&综艺&动漫',
    class_url: '1&2&3&4',
    play_parse: true,
    lazy: "js:\n  let html = request(input);\n  let hconf = html.match(/r player_.*?=(.*?)</)[1];\n  let json = JSON5.parse(hconf);\n  let url = json.url;\n  if (json.encrypt == '1') {\n    url = unescape(url);\n  } else if (json.encrypt == '2') {\n    url = unescape(base64Decode(url));\n  }\n  if (/\\.(m3u8|mp4|m4a|mp3)/.test(url)) {\n    input = {\n      parse: 0,\n      jx: 0,\n      url: url,\n    };\n  } else {\n    input = url && url.startsWith('http') && tellIsJx(url) ? {parse:0,jx:1,url:url}:input;\n  }",
    limit: 6,
    double: true,
    推荐: 'ul.myui-vodlist.clearfix;li;a&&title;img&&data-original;.pic-text&&Text;a&&href',
    double: true,
    一级: '.myui-vodlist li;a&&title;img&&data-original;.pic-text.text-right&&Text;a&&href',
    二级: {
        title: '.myui-content__detail .title--span&&Text;.myui-content__detail p.data:eq(3)&&Text',
        img: '.myui-content__thumb .lazyload&&data-original',
        desc: '.myui-content__detail p.otherbox&&Text;.year&&Text;.myui-content__detail p.data:eq(4)&&Text;.myui-content__detail p.data:eq(2)&&Text;.myui-content__detail p.data:eq(0)&&Text',
        content: '.desc.text-collapse&&span:eq(1)&&Text',
        tabs: '.nav-tabs:eq(0) li',
        lists: '.myui-content__list:eq(#id) li',
    },
    搜索: '#searchList li;a&&title;.lazyload&&data-original;.pic-text&&Text;a&&href;.detail&&Text',
    filter: {
        '1': [{ key: '类型', name: '类型', value: [{ n: '动作片', v: '5', }, { n: '爱情片', v: '6', }, { n: '科幻片', v: '7', }, { n: '恐怖片', v: '8', }, { n: '战争片', v: '9', }, { n: '喜剧片', v: '10', }, { n: '纪录片', v: '11', }, { n: '剧情片', v: '12', }, { n: '奇幻片', v: '28', },], }, { key: '地区', name: '地区', value: [{ n: '全部', v: '', }, { n: '大陆', v: '大陆', }, { n: '香港', v: '香港', }, { n: '台湾', v: '台湾', }, { n: '美国', v: '美国', }, { n: '英国', v: '英国', }, { n: '日本', v: '日本', }, { n: '韩国', v: '韩国', }, { n: '泰国', v: '泰国', }, { n: '印度', v: '印度', }, { n: '加拿大', v: '加拿大', }, { n: '法国', v: '法国', }, { n: '西班牙', v: '西班牙', }, { n: '德国', v: '德国', }, { n: '其它', v: '其它', },], }, { key: '年份', name: '年份', value: [{ n: '全部', v: '', }, { n: '2025', v: '2025', }, { n: '2024', v: '2024', }, { n: '2023', v: '2023', }, { n: '2022', v: '2022', }, { n: '2021', v: '2021', }, { n: '2020', v: '2020', }, { n: '2019', v: '2019', }, { n: '2018', v: '2018', }, { n: '2017', v: '2017', }, { n: '2016', v: '2016', }, { n: '2015', v: '2015', }, { n: '2014', v: '2014', }, { n: 'more', v: 'more', },], }, { key: '排序', name: '排序', value: [{ n: '更新时间', v: 'time', }, { n: '人气', v: 'hit', }, { n: '豆瓣评分', v: 'douban', }, { n: '站内评分', v: 'score', },], },],
        '2': [{ key: '类型', name: '类型', value: [{ n: '国产剧', v: '13', }, { n: '港剧', v: '14', }, { n: '短剧', v: '67', }, { n: '欧美剧', v: '15', }, { n: '韩剧', v: '31', }, { n: '日剧', v: '16', }, { n: '台剧', v: '30', }, { n: '其他剧', v: '29', },], }, { key: '地区', name: '地区', value: [{ n: '全部', v: '', }, { n: '大陆', v: '大陆', }, { n: '香港', v: '香港', }, { n: '台湾', v: '台湾', }, { n: '美国', v: '美国', }, { n: '英国', v: '英国', }, { n: '日本', v: '日本', }, { n: '韩国', v: '韩国', }, { n: '泰国', v: '泰国', }, { n: '印度', v: '印度', }, { n: '加拿大', v: '加拿大', }, { n: '法国', v: '法国', }, { n: '西班牙', v: '西班牙', }, { n: '德国', v: '德国', }, { n: '其它', v: '其它', },], }, { key: '年份', name: '年份', value: [{ n: '全部', v: '', }, { n: '2025', v: '2025', }, { n: '2024', v: '2024', }, { n: '2023', v: '2023', }, { n: '2022', v: '2022', }, { n: '2021', v: '2021', }, { n: '2020', v: '2020', }, { n: '2019', v: '2019', }, { n: '2018', v: '2018', }, { n: '2017', v: '2017', }, { n: '2016', v: '2016', }, { n: '2015', v: '2015', }, { n: '2014', v: '2014', }, { n: 'more', v: 'more', },], }, { key: '排序', name: '排序', value: [{ n: '更新时间', v: 'time', }, { n: '人气', v: 'hit', }, { n: '豆瓣评分', v: 'douban', }, { n: '站内评分', v: 'score', },], },],
        '3': [{ key: '地区', name: '地区', value: [{ n: '全部', v: '', }, { n: '大陆', v: '大陆', }, { n: '香港', v: '香港', }, { n: '台湾', v: '台湾', }, { n: '美国', v: '美国', }, { n: '英国', v: '英国', }, { n: '日本', v: '日本', }, { n: '韩国', v: '韩国', }, { n: '泰国', v: '泰国', }, { n: '印度', v: '印度', }, { n: '加拿大', v: '加拿大', }, { n: '法国', v: '法国', }, { n: '西班牙', v: '西班牙', }, { n: '德国', v: '德国', }, { n: '其它', v: '其它', },], }, { key: '年份', name: '年份', value: [{ n: '全部', v: '', }, { n: '2025', v: '2025', }, { n: '2024', v: '2024', }, { n: '2023', v: '2023', }, { n: '2022', v: '2022', }, { n: '2021', v: '2021', }, { n: '2020', v: '2020', }, { n: '2019', v: '2019', }, { n: '2018', v: '2018', }, { n: '2017', v: '2017', }, { n: '2016', v: '2016', }, { n: '2015', v: '2015', }, { n: '2014', v: '2014', }, { n: 'more', v: 'more', },], }, { key: '排序', name: '排序', value: [{ n: '更新时间', v: 'time', }, { n: '人气', v: 'hit', }, { n: '站内评分', v: 'score', },], },],
        '4': [{ key: '地区', name: '地区', value: [{ n: '全部', v: '', }, { n: '大陆', v: '大陆', }, { n: '香港', v: '香港', }, { n: '台湾', v: '台湾', }, { n: '美国', v: '美国', }, { n: '英国', v: '英国', }, { n: '日本', v: '日本', }, { n: '韩国', v: '韩国', }, { n: '泰国', v: '泰国', }, { n: '印度', v: '印度', }, { n: '加拿大', v: '加拿大', }, { n: '法国', v: '法国', }, { n: '西班牙', v: '西班牙', }, { n: '德国', v: '德国', }, { n: '其它', v: '其它', },], }, { key: '年份', name: '年份', value: [{ n: '全部', v: '', }, { n: '2025', v: '2025', }, { n: '2024', v: '2024', }, { n: '2023', v: '2023', }, { n: '2022', v: '2022', }, { n: '2021', v: '2021', }, { n: '2020', v: '2020', }, { n: '2019', v: '2019', }, { n: '2018', v: '2018', }, { n: '2017', v: '2017', }, { n: '2016', v: '2016', }, { n: '2015', v: '2015', }, { n: '2014', v: '2014', }, { n: 'more', v: 'more', },], }, { key: '排序', name: '排序', value: [{ n: '更新时间', v: 'time', }, { n: '人气', v: 'hit', }, { n: '豆瓣评分', v: 'douban', }, { n: '站内评分', v: 'score', },], },],
    },
    filter_url: 'page=fypage&searchtype=5&order={{fl.排序}}&tid={{fl.类型}}&area={{fl.地区}}&year={{fl.年份}}&letter=&yuyan=&state=&money=&ver=&jq=',
    filter_def: { 1: { 类型: '1' }, 2: { 类型: '2' }, 3: { 类型: '3' }, 4: { 类型: '4' } },
}