var rule = {
   title: '美剧窝',
   host: 'https://www.mjwo.net',
   //url: '/type/fyclass-fypage/',
   url: '/show/fyfilter/',
   searchUrl: 'https://www.mjwo.net/search/**--/page/fypage/',
   searchable: 2,//是否启用全局搜索,
   quickSearch: 0,//是否启用快速搜索,
   filterable: 1,//是否启用分类筛选,
   headers: {//网站的请求头,完整支持所有的,常带ua和cookies
      'User-Agent': 'MOBILE_UA', // "Cookie": "searchneed=ok"
   },
   class_parse: '.nav-list li:lt(4);a&&Text;a&&href;.*/(.*?)/',
   cate_exclude: '明星|永久|更新',
   play_parse: true,
   lazy: '',
   limit: 6,
   filter: {
      "dianying": [{ key: '类型', name: '类型', value: [{ n: '全部', v: '', }, { n: '动作片', v: 'dongzuopian', }, { n: '喜剧片', v: 'xijupian', }, { n: '爱情片', v: 'aiqingpian', }, { n: '科幻片', v: 'kehuanpian', }, { n: '恐怖片', v: 'kongbupian', }, { n: '剧情片', v: 'juqingpian', }, { n: '战争片', v: 'zhanzhengpian', }, { n: '动画片', v: 'donghuapian', },], }, { key: '剧情', name: '剧情', value: [{ n: '全部', v: '', }, { n: '剧情', v: '/class/剧情', }, { n: '喜剧', v: '/class/喜剧', }, { n: '爱情', v: '/class/爱情', }, { n: '动作', v: '/class/动作', }, { n: '惊悚', v: '/class/惊悚', }, { n: '悬疑', v: '/class/悬疑', }, { n: '恐怖', v: '/class/恐怖', }, { n: '犯罪', v: '/class/犯罪', }, { n: '科幻', v: '/class/科幻', }, { n: '冒险', v: '/class/冒险', }, { n: '奇幻', v: '/class/奇幻', }, { n: '动画', v: '/class/动画', }, { n: '战争', v: '/class/战争', }, { n: '历史', v: '/class/历史', }, { n: '音乐', v: '/class/音乐', }, { n: '古装', v: '/class/古装', }, { n: '家庭', v: '/class/家庭', }, { n: '武侠', v: '/class/武侠', }, { n: '纪录', v: '/class/纪录', }, { n: '灾难', v: '/class/灾难', }, { n: '运动', v: '/class/运动', }, { n: '传记', v: '/class/传记', }, { n: '歌舞', v: '/class/歌舞', }, { n: '儿童', v: '/class/儿童', }, { n: '西部', v: '/class/西部', },], }, { key: '地区', name: '地区', value: [{ n: '全部', v: '', }, { n: '香港', v: '/area/香港', }, { n: '台湾', v: '/area/台湾', }, { n: '韩国', v: '/area/韩国', }, { n: '日本', v: '/area/日本', }, { n: '美国', v: '/area/美国', }, { n: '法国', v: '/area/法国', }, { n: '英国', v: '/area/英国', }, { n: '泰国', v: '/area/泰国', }, { n: '印度', v: '/area/印度', }, { n: '新加坡', v: '/area/新加坡', }, { n: '其它', v: '/area/其它', },], }, { key: '年份', name: '年份', value: [{ n: '全部', v: '', }, { n: '2025', v: '/year/2025', }, { n: '2024', v: '/year/2024', }, { n: '2023', v: '/year/2023', }, { n: '2022', v: '/year/2022', }, { n: '2021', v: '/year/2021', }, { n: '2020', v: '/year/2020', }, { n: '2010-2019', v: '/year/2010-2019', }, { n: '2000-2009', v: '/year/2000-2009', }, { n: '1990-1999', v: '/year/1990-1999', }, { n: '1980-1989', v: '/year/1980-1989', }, { n: '1800-1979', v: '/year/1800-1979', },], }, { key: '状态', name: '状态', value: [{ n: '全部', v: '', }, { n: '完结', v: '/isend/完结', }, { n: '连载', v: '/isend/连载', },], }, { key: '排序', name: '排序', value: [{ n: '时间', v: '/by/time', }, { n: '人气', v: '/by/hits', }, { n: '评分', v: '/by/score', },], },],
      "gangju": [{ key: '剧情', name: '剧情', value: [{ n: '全部', v: '', }, { n: '剧情', v: '/class/剧情', }, { n: '喜剧', v: '/class/喜剧', }, { n: '爱情', v: '/class/爱情', }, { n: '动作', v: '/class/动作', }, { n: '惊悚', v: '/class/惊悚', }, { n: '悬疑', v: '/class/悬疑', }, { n: '恐怖', v: '/class/恐怖', }, { n: '犯罪', v: '/class/犯罪', }, { n: '科幻', v: '/class/科幻', }, { n: '冒险', v: '/class/冒险', }, { n: '奇幻', v: '/class/奇幻', }, { n: '战争', v: '/class/战争', }, { n: '历史', v: '/class/历史', }, { n: '古装', v: '/class/古装', }, { n: '家庭', v: '/class/家庭', }, { n: '武侠', v: '/class/武侠', }, { n: '生活', v: '/class/生活', }, { n: '灾难', v: '/class/灾难', }, { n: '歌舞', v: '/class/歌舞', }, { n: '预告', v: '/class/预告', }, { n: '都市', v: '/class/都市', }, { n: '传奇', v: '/class/传奇', }, { n: '穿越', v: '/class/穿越', }, { n: '动画', v: '/class/动画', }, { n: '传记', v: '/class/传记', }, { n: '偶像', v: '/class/偶像', }, { n: '校园', v: '/class/校园', }, { n: '青春', v: '/class/青春', }, { n: '运动', v: '/class/运动', }, { n: '同性', v: '/class/同性', }, { n: '西部', v: '/class/西部', }, { n: '纪录', v: '/class/纪录', }, { n: '音乐', v: '/class/音乐', },], }, { key: '年份', name: '年份', value: [{ n: '全部', v: '', }, { n: '2025', v: '/year/2025', }, { n: '2024', v: '/year/2024', }, { n: '2023', v: '/year/2023', }, { n: '2022', v: '/year/2022', }, { n: '2021', v: '/year/2021', }, { n: '2020', v: '/year/2020', }, { n: '2010-2019', v: '/year/2010-2019', }, { n: '2000-2009', v: '/year/2000-2009', }, { n: '1990-1999', v: '/year/1990-1999', }, { n: '1980-1989', v: '/year/1980-1989', }, { n: '1800-1979', v: '/year/1800-1979', },], }, { key: '状态', name: '状态', value: [{ n: '全部', v: '', }, { n: '完结', v: '/isend/完结', }, { n: '连载', v: '/isend/连载', },], }, { key: '排序', name: '排序', value: [{ n: '排序', v: '', }, { n: '时间', v: '/by/time', }, { n: '人气', v: '/by/hits', }, { n: '评分', v: '/by/score', },], },],
      "meiju": [{ key: '剧情', name: '剧情', value: [{ n: '全部', v: '', }, { n: '剧情', v: '/class/剧情', }, { n: '喜剧', v: '/class/喜剧', }, { n: '爱情', v: '/class/爱情', }, { n: '动作', v: '/class/动作', }, { n: '惊悚', v: '/class/惊悚', }, { n: '悬疑', v: '/class/悬疑', }, { n: '恐怖', v: '/class/恐怖', }, { n: '犯罪', v: '/class/犯罪', }, { n: '科幻', v: '/class/科幻', }, { n: '冒险', v: '/class/冒险', }, { n: '奇幻', v: '/class/奇幻', }, { n: '战争', v: '/class/战争', }, { n: '历史', v: '/class/历史', }, { n: '古装', v: '/class/古装', }, { n: '家庭', v: '/class/家庭', }, { n: '武侠', v: '/class/武侠', }, { n: '生活', v: '/class/生活', }, { n: '灾难', v: '/class/灾难', }, { n: '歌舞', v: '/class/歌舞', }, { n: '预告', v: '/class/预告', }, { n: '都市', v: '/class/都市', }, { n: '传奇', v: '/class/传奇', }, { n: '穿越', v: '/class/穿越', }, { n: '动画', v: '/class/动画', }, { n: '传记', v: '/class/传记', }, { n: '偶像', v: '/class/偶像', }, { n: '校园', v: '/class/校园', }, { n: '青春', v: '/class/青春', }, { n: '运动', v: '/class/运动', }, { n: '同性', v: '/class/同性', }, { n: '西部', v: '/class/西部', }, { n: '纪录', v: '/class/纪录', }, { n: '音乐', v: '/class/音乐', },], }, { key: '年份', name: '年份', value: [{ n: '全部', v: '', }, { n: '2025', v: '/year/2025', }, { n: '2024', v: '/year/2024', }, { n: '2023', v: '/year/2023', }, { n: '2022', v: '/year/2022', }, { n: '2021', v: '/year/2021', }, { n: '2020', v: '/year/2020', }, { n: '2010-2019', v: '/year/2010-2019', }, { n: '2000-2009', v: '/year/2000-2009', }, { n: '1990-1999', v: '/year/1990-1999', }, { n: '1980-1989', v: '/year/1980-1989', }, { n: '1800-1979', v: '/year/1800-1979', },], }, { key: '状态', name: '状态', value: [{ n: '全部', v: '', }, { n: '完结', v: '/isend/完结', }, { n: '连载', v: '/isend/连载', },], }, { key: '排序', name: '排序', value: [{ n: '时间', v: '/by/time', }, { n: '人气', v: '/by/hits', }, { n: '评分', v: '/by/score', },], },],
   },
   filter_url: '{{fl.类型}}{{fl.地区}}{{fl.排序}}{{fl.剧情}}{{fl.状态}}/page/fypage{{fl.year}}',
   filter_def: { dianying: { 类型: 'dianying' }, gangju: { 类型: 'gangju' }, meiju: { 类型: 'meiju' } },
   推荐: 'ul.myui-vodlist.clearfix;li;a&&title;a&&data-original;.pic-text&&Text;a&&href',
   double: true, // 推荐内容是否双层定位
   一级: '.myui-vodlist li;a&&title;a&&data-original;.pic-text&&Text;a&&href',
   二级: {
      "title": ".myui-content__detail .title&&Text;.myui-content__detail p:eq(-2)&&Text",
      "img": ".myui-content__thumb .lazyload&&data-original",
      "desc": ".myui-content__detail p:eq(0)&&Text;.myui-content__detail p:eq(1)&&Text;.myui-content__detail p:eq(2)&&Text",
      "content": ".content&&Text",
      "tabs": ".myui-panel__head.active.bottom-line h3",
      "lists": ".myui-content__list:eq(#id) a"
   },
   搜索: '#searchList li;a&&title;.lazyload&&data-original;.pic-text&&Text;a&&href;.detail&&p:eq(1) p&&Text',
}