var rule = {
  title:'西瓜影院',
  host:'https://www.a6club.com/',
  url:'/index.php/vod/show/fyfilter.html',
  searchUrl:'/index.php/vod/search/page/fypage/wd/**.html',
  class_name: '电影&电视剧&综艺&动漫&B站',
  class_url: '20&37&45&43&47',
  searchable: 2,
  quickSearch: 0,
  headers: {'User-Agent': 'MOBILE_UA',},
  filterable: 1,
  filter: 'H4sIAAAAAAAAA+2b0U4bRxSG38XXSJ7ZtXfGuexrVLlwW0tFbVKJpJVQFKkNgXiBhhCBqQNJU6nGQEhslBSVNYaX8czaV3mFrm3s+ecklXJh+epc7vlOvOtvV/FnBA9ygcjd+vpB7ofKcu5WLj3rmFcbuYXc3fKdCh7/Uv7x58po8W42NqtHg5Wj4Tg7yD1cuJmuH/W6B2n85AYsfpcPpKO1AxM3fRpMaVo9syurPg0dbW6bi45PC1Nqf3tmf635tOjOGzc/eeXI/dvqH70k9qlydGXdPnrhU+2uar2Vdk98WnLnXXs+qB+nLaChQFfpjv+OQufKPjpNa9s+da7s28Pe1WufOlem8YS6Cp2rNDkx3V2fgqvV817HNxlmrm4P+fgBMQdts5m4B2R6/EUPyN/NQX3tZlpeqpTz40l+ujE4rNt/W7gxnrgNs9W2F1fea4wmbiO9emr2u7gxnsBZ/jwmG+OJ27B7DXtwihvjCWy8b5PXGE9go9Y266/Ny7+8pckQrub41L5s9BvXveSFd00wh/f/e9skh977H03cRn/jjFzZeILXvvvJte96G9k12o3r7O54J5oM4VyN63TrbRrXvdNNhm6vd/047e7Zmndrp8M8PoDm3Yp30tEk7z+EFx96nS48hJPjL3kIA5H95zCe5Zcr5aX8aAC0QGkBaUhpiDSgNEAqKZVIBaUCqCwRKktINaUaqaJUIY0ojZBSVxJdSepKoitJXUl0Jakria4kdSXRlaSuJLoS1JVAV4K6EuhKUFcCXQnqSqArQV0JdCWoK4GuBHUl0JWgrgS6EtSVQFeCuhLOlSyVfFejAVBNqUaqKFVII0ojpEVKi0gLlBaQhpSGSANKA6SSUolUUIquNHWl0ZWmrjS60tSVRleautLoSlNXGl1p6kqjK01daXSlqSuNrjR1pdGVpq40ulLUlUJXirpS6EpRVwpdKepKoStFXSl0pagrha4UdaXQlaKuFLpS1JVCV4q6Uugqoq4idBVRVxG6iqirCF1F1FWEriLqKhvgx6x9+twkW+5jdnrsf8zazdjunQ/2Pty82jfL+fuLdyqQG5txL0lse8ctfL94/5630G89NtU1t3Dv25+WKqNP/dsLuVDN7CvKfreXNLOvBBC4TmcWmllM+tTdCnvaHIYk0oK7jVkfDiPSo/DlZxTWPg04rDmsOaw5rDmsOaw5rDmsOaw5rOcb1oVwhj/7t5dvoG4LXLdct1y3XLdct1y3XLdct1y3XLdzrtvirOo27Vz24wTqln8pguuW65brluuW65brluuW65brdt51O7Nfikh3T0zc/HhZ/Sp9U/94GUPnOqtZCZnq/meX3I1Jd/4x3bPPLRUFLvWba/9zxqLksuay5rLmsuay5rLmsuay5rLmsp5vWReDWZV1//x9+mzSF8O6hT9pbL3zEfyNXnfbR+6Zyuql30rM6gZQ/lk0FzMXMxczFzMXMxczFzMXMxfzXIv54X/SIWHdRUQAAA==',
  filter_url: '{{fl.地区}}{{fl.排序}}{{fl.类型}}/page/fypage{{fl.年份}}',
  filter_def: {20:{类型:"id/20"},37:{类型:"id/37"},45:{类型:"id/45"},43:{类型:"id/43"},47:{类型:"id/47"},},
  detailUrl: '/index.php/vod/detail/id/fyid.html',
  play_parse: true,
  lazy: "js:\n  let html = request(input);\n  let hconf = html.match(/r player_.*?=(.*?)</)[1];\n  let json = JSON5.parse(hconf);\n  let url = json.url;\n  if (json.encrypt == '1') {\n    url = unescape(url);\n  } else if (json.encrypt == '2') {\n    url = unescape(base64Decode(url));\n  }\n  if (/\\.(m3u8|mp4|m4a|mp3)/.test(url)) {\n    input = {\n      parse: 0,\n      jx: 0,\n      url: url,\n    };\n  } else {\n    input = url && url.startsWith('http') && tellIsJx(url) ? {parse:0,jx:1,url:url}:input;\n  }",
  limit: 6,
  推荐: '.movie-list-body.flex;.movie-title&&Text;.movie-post-lazyload&&data-original;.movie-rating&&Text;a&&href',
  一级: '.movie-list-item;.movie-title&&Text;.movie-post-lazyload&&data-original;.movie-rating&&Text;a&&href',
  二级: {
    title: '.movie-title&&Text;.cr3&&Text',
    img: '.poster&&img&&src',
    desc: '.scroll-content&&Text;.scroll-content&&a:eq(3)&&Text;.scroll-content&&a:eq(4)&&Text;.cr3.starLink&&Text',
    content: '.detailsTxt&&Text',
    tabs: '.play_source_tab&&a',
    tab_text: 'a--span&&Text',
    lists: '.content_playlist:eq(#id) li',
  },
  搜索: '.vod-search-list;.movie-title&&Text;.movie-post-lazyload&&data-original;.movie-rating&&Text;a&&href',
}